@ECHO OFF

SET BLENDER_USER_CONFIG=%CD%\config
SET BLENDER_USER_SCRIPTS=%CD%\scripts

if EXIST %BLENDER_USER_CONFIG%\userpref.blend DEL /P %BLENDER_USER_CONFIG%\userpref.blend
if EXIST %BLENDER_USER_CONFIG%\startup.blend DEL /P %BLENDER_USER_CONFIG%\startup.blend

IF NOT EXIST %BLENDER_USER_CONFIG% MKDIR %BLENDER_USER_CONFIG%

CALL %BLENDER_INSTALL_DIR%\blender270.lnk  --background --python %CD%\myprefs.py

PAUSE
